name: pokemon_tracker
description: A Flutter app for Pokedex
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.5.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  google_generative_ai: ^0.2.3
  go_router: ^13.2.2
  intl: ^0.18.1
  page_transition: ^2.1.0
  sizer: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - .env
